Concurrent CI (#365)

diff --git a/bin/test-all-exercises b/bin/test-all-exercises
--- a/bin/test-all-exercises
+++ b/bin/test-all-exercises
@@ -1,22 +1,25 @@
 #!/bin/sh
 
-test_one=$(dirname $0)/test-exercise
-exercises=$(dirname $(dirname $0))/exercises
-status=0
-failed_exercises=""
-
-# TODO: To be confirmed: Would use this line when there are any concept exercises
-#for d in $exercises/{concept,practice}/*/; do
-for d in $exercises/practice/*; do
-  if ! $test_one $d; then
-    failed_exercises="$failed_exercises\n$(basename $d)"
-    status=1
-  fi
+jobs=1
+while getopts "j:" opt; do
+  case "$opt" in
+    j) jobs="$OPTARG" ;;
+    *) exit 1 ;;
+  esac
 done
 
-if [ $status -ne 0 ]; then
-  echo "The following exercises failed"
-  echo $failed_exercises
-fi
+test_one=$(dirname "$0")/test-exercise
+exercises=$(dirname "$(dirname "$0")")/exercises
 
-exit $status
+failed_file=$(mktemp)
+trap 'rm -f "$failed_file"' EXIT
+
+# shellcheck disable=SC2016
+cmd=$(printf '"%s" "$1" || basename "$1" >> "%s"' "$test_one" "$failed_file")
+printf '%s\n' "$exercises"/practice/*/ | xargs -P "$jobs" -I{} sh -c "${cmd}" _ "{}"
+
+if [ -s "$failed_file" ]; then
+  echo "The following exercises failed"
+  cat "$failed_file"
+  exit 1
+fi
