copy tests from stub to example, instead of duplicating tests
This relieves contributors of having the burden of making all tests
changes in two places.

Closes https://github.com/exercism/d/issues/43

EXPECTED COMPILE FAILURE in crypto-square:
Its example solution's interface does not match the interface expected
by the stub's tests (`normalizedCipherText` vs `normalize.cipherText`).
This discrepancy has existed ever since `crypto-square` was added.
The compile failure serves to verify that CI is correctly copying and
running tests.

diff --git a/bin/test-exercise b/bin/test-exercise
--- a/bin/test-exercise
+++ b/bin/test-exercise
@@ -12,14 +12,26 @@ cd $dir
 status=0
 
 mv source testbak
-mv example source
+cp -r example source
+# copy unittests from stub to example
+# can't do >> *.d, so get the filename of the source file.
+src=$(ls source/*.d)
+sed -n '/unittest/,$ p' testbak/*.d >> $src
+if ! grep -q unittest $src ; then
+  echo "$dir failed to copy tests into example"
+  status=1
+fi
+# find any line that contains both `if` and `allTestsEnabled`,
+# and change the `allTestsEnabled` in that line to `true`
+# Thus, making all tests run.
+sed -i'' -e 's/if\(.*\)allTestsEnabled\(.*\)/if\1true\2/' $src
 if ! dub test ; then
   echo "$dir test has failed"
   status=1
 fi
 # Restore so that if we are running locally,
 # we don't accidentally commit the directory moves.
-mv source example
+rm -r source
 mv testbak source
 
 exit $status
